[package]
name = "camelup-server"
version = "0.1.0"
authors = ["aragonet <c.aragon.seb@gmail.com>"]
edition = "2018"

[dependencies] 
rand = "0.7"
ws = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"